config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'shop' => 'static_pages#shop'

  get 'testimonials' => 'static_pages#testimonials'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def shop
  end

  def testimonials
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstrapProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="container">

  <div class="masthead">
   <h3 class="text-muted">All About Us</h3>
  </div>

  <div class="jumbotron">
    <h1>Humble beginnings</h1>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h2>Once upon a time...</h2>
      <p>When we were dazed and confused</p>
      <%= link_to "Home", root_path, class: 'btn btn-primary' %>
    </div>

    <!-- <div class="col-md-4">
      <h2>About</h2>
      <p>We have heritage for finely brewed coffees</p>
      <%= link_to "Read More", about_path, class: 'btn btn-primary' %>
    </div>

    <div class="col-md-4">
      <h2>Buy</h2>
      <p>Shop through our online store here.</p>
      <%= link_to "Buy Now", shop_path, class: 'btn btn-primary' %>
    </div> -->
  </div>

</div>

app/views/static_pages/home.html.erb
<div class="container">

  <div class="masthead">
   <h3 class="text-muted">Coffeeshop</h3>
  </div>

  <div class="jumbotron">
    <h1>Stanley's Special Coffee Blend</h1>
    <p class="lead">The best coffee on the West Coast. Order 5 and get one free today!!!! :-)</p>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h2>How good is this coffee?</h2>
      <p>This coffee is so good that it'll blow your socks off</p>
      <%= link_to "Read testimonial", testimonials_path, class: 'btn btn-primary' %>
    </div>

    <div class="col-md-4">
      <h2>About</h2>
      <p>We have heritage for finely brewed coffees</p>
      <%= link_to "Read More", about_path, class: 'btn btn-primary' %>
    </div>

    <div class="col-md-4">
      <h2>Buy</h2>
      <p>Shop through our online store here.</p>
      <%= link_to "Buy Now", shop_path, class: 'btn btn-primary' %>
    </div>

  </div>
</div>

app/views/static_pages/shop.html.erb
<h1>StaticPages#shop</h1>
<p>Find me in app/views/static_pages/shop.html.erb</p>

app/views/static_pages/testimonials.html.erb
<h1>StaticPages#testimonial</h1>
<p>Find me in app/views/static_pages/testimonial.html.erb</p>
<%= link_to "Home", root_path, class: 'btn btn-primary' %>